"""
safe_executor.py
-----------------
Executes a single pandas expression generated by the LLM, against an
in-memory dataframe, under deliberate restrictions.

Why this exists (this is the file to defend in an interview):
LLMs can and do generate code that isn't malicious on purpose but is
still unsafe to run blindly - it might try to read/write files, import
modules, or call something expensive/unexpected. Since the code here
is machine-generated and only lightly reviewed by a human at request
time, we don't trust it the way we'd trust our own code. Instead of
"eval() and hope", we:

  1. Restrict the expression to a single line (no statements, no
     function/class definitions, no loops).
  2. Reject anything containing blocklisted tokens (import, exec, eval,
     open, __, os., sys., subprocess, etc.).
  3. Execute with a minimal globals/builtins dict - only `pd` and `df`
     are available, nothing else from the real Python environment.
  4. Only ever accept a pandas DataFrame/Series/scalar as the result -
     anything else is rejected rather than returned to the client.

This is not a full sandbox (true isolation would mean a separate
process or container) - documented explicitly as a known limitation
and a "next step for production hardening" in the README, rather than
overclaiming safety it doesn't have.
"""

from __future__ import annotations

import logging
import re

import pandas as pd

logger = logging.getLogger("recruiter_tool.safe_executor")

BLOCKED_TOKENS = [
    "import", "exec", "eval", "open(", "__", "os.", "sys.",
    "subprocess", "globals", "locals", "compile(", "input(",
    ".to_csv", ".to_excel", ".to_pickle", ".to_sql", "shutil",
    "socket", "requests", "urllib", "pd.read_", "lambda",
]

MAX_EXPRESSION_LENGTH = 400


class UnsafeExpressionError(Exception):
    pass


class ExecutionError(Exception):
    pass


def validate_expression(expr: str) -> None:
    if not expr or not isinstance(expr, str):
        raise UnsafeExpressionError("Empty or non-string expression.")

    if len(expr) > MAX_EXPRESSION_LENGTH:
        raise UnsafeExpressionError("Expression exceeds maximum allowed length.")

    if "\n" in expr or ";" in expr:
        raise UnsafeExpressionError("Multi-statement expressions are not allowed.")

    lowered = expr.lower()
    for token in BLOCKED_TOKENS:
        if token in lowered:
            raise UnsafeExpressionError(f"Expression contains disallowed token: '{token}'")

    # Must reference the dataframe - otherwise it isn't a real query
    if "df" not in expr:
        raise UnsafeExpressionError("Expression does not reference 'df'.")


def run_expression(expr: str, df: pd.DataFrame):
    """
    Validates and executes `expr` against `df`.
    Returns a pandas DataFrame/Series/scalar result.
    Raises UnsafeExpressionError or ExecutionError on failure -
    caller is expected to turn these into a clean API error response,
    never a raw traceback shown to the end user.
    """
    validate_expression(expr)

    restricted_globals = {"__builtins__": {}}
    restricted_locals = {"pd": pd, "df": df}

    try:
        result = eval(expr, restricted_globals, restricted_locals)  # noqa: S307
    except Exception as e:  # noqa: BLE001
        logger.warning("Execution failed for expression=%r error=%s", expr, e)
        raise ExecutionError(str(e)) from e

    if not isinstance(result, (pd.DataFrame, pd.Series, int, float, str, bool)):
        raise UnsafeExpressionError(
            f"Expression returned disallowed type: {type(result)}"
        )

    logger.info("Executed expression=%r successfully", expr)
    return result
