"""
safe_editor.py
--------------
Applies edits to the dataframe. This is the ONLY place in the codebase
allowed to mutate data, and it deliberately does NOT let the LLM
generate and execute arbitrary code to do it.

Why this is stricter than safe_executor.py (the read-only query path):
Getting a read wrong returns a bad answer, which the user can catch by
eye. Getting a WRITE wrong silently corrupts real business data with
no obvious symptom, potentially not noticed until much later. So while
safe_executor.py accepts a validated pandas *expression* generated by
the LLM, this module does NOT execute LLM-generated code at all - it
only accepts a small, closed set of named operations with typed
parameters. The LLM's job is to figure out WHICH operation and
parameters fit the user's request; it never gets to write the
execution logic itself.

Every operation here:
  - is scoped to specific rows/columns, never "the whole table"
  - returns a diff preview (before/after) for the audit log
  - is easy to describe in one sentence, on purpose
"""

from __future__ import annotations

import logging

import pandas as pd

from app import column_formula

logger = logging.getLogger("ad_intel.safe_editor")


class EditValidationError(Exception):
    pass


def _preview(df: pd.DataFrame, row_indices: list, column: str, new_value) -> list:
    preview = []
    for idx in row_indices[:5]:
        preview.append({
            "row": int(idx),
            "column": column,
            "before": df.at[idx, column] if column in df.columns else None,
            "after": new_value,
        })
    return preview


def fill_missing_value(df: pd.DataFrame, column: str, row_indices: list, value: str) -> tuple[pd.DataFrame, list]:
    """Fills missing/blank values in `column` for the given rows with `value`.
    Refuses to touch rows that are NOT actually missing - this operation
    is for filling gaps, not overwriting existing data (use
    standardize_value for that)."""
    if column not in df.columns:
        raise EditValidationError(f"Column '{column}' does not exist.")

    new_df = df.copy(deep=True)
    target_rows = [
        idx for idx in row_indices
        if idx in new_df.index and (pd.isna(new_df.at[idx, column]) or str(new_df.at[idx, column]).strip() == "")
    ]
    if not target_rows:
        raise EditValidationError("None of the specified rows have a missing value in this column.")

    preview = _preview(new_df, target_rows, column, value)
    new_df.loc[target_rows, column] = value
    return new_df, preview


def standardize_value(df: pd.DataFrame, column: str, row_indices: list, new_value: str) -> tuple[pd.DataFrame, list]:
    """Overwrites `column` for the given (existing, non-missing) rows
    with `new_value` - e.g. reconciling name variants to one spelling.
    Requires explicit row_indices (from a prior diagnostics call) rather
    than a free-text match condition, so the agent can't accidentally
    rewrite more rows than the user actually saw and approved."""
    if column not in df.columns:
        raise EditValidationError(f"Column '{column}' does not exist.")
    if not row_indices:
        raise EditValidationError("No row indices provided - refusing to run an unscoped edit.")

    valid_rows = [idx for idx in row_indices if idx in df.index]
    if not valid_rows:
        raise EditValidationError("None of the specified rows exist in the current data.")

    new_df = df.copy(deep=True)
    preview = _preview(new_df, valid_rows, column, new_value)
    new_df.loc[valid_rows, column] = new_value
    return new_df, preview


def fill_missing_value_bulk(df: pd.DataFrame, column: str, value: str) -> tuple[pd.DataFrame, list]:
    """Fills EVERY missing value in `column`, recomputed fresh at edit
    time rather than relying on a row-index list the agent may have only
    seen a truncated sample of.

    Why this exists as a separate operation from fill_missing_value:
    diagnostics results are capped (e.g. to the first 20 rows) so the
    LLM's context isn't flooded on a large dataset. If "fix all 138
    missing rows" were implemented by asking the agent to pass back the
    row_indices it saw in the previous tool result, it would silently
    only fix the 20 it had - a real bug, caught by testing this against
    the actual 11k-row file rather than a small synthetic example. This
    operation sidesteps that entirely: it re-derives the complete set of
    missing rows itself, so "fix all" always means all of them."""
    if column not in df.columns:
        raise EditValidationError(f"Column '{column}' does not exist.")

    new_df = df.copy(deep=True)
    missing_mask = new_df[column].isna() | (new_df[column].astype(str).str.strip() == "")
    target_rows = new_df[missing_mask].index.tolist()
    if not target_rows:
        raise EditValidationError(f"No missing values found in '{column}'.")

    preview = _preview(new_df, target_rows, column, value)
    new_df.loc[target_rows, column] = value
    return new_df, preview


def flag_rows(df: pd.DataFrame, row_indices: list, flag_column: str, flag_value: str) -> tuple[pd.DataFrame, list]:
    """Adds/updates a review flag column on specific rows without
    touching the original fields - use this when the answer to a
    problem is 'mark for human review' rather than a direct data
    change, e.g. tagging suspected near-duplicate advertisers."""
    if not row_indices:
        raise EditValidationError("No row indices provided.")

    new_df = df.copy(deep=True)
    if flag_column not in new_df.columns:
        new_df[flag_column] = ""

    valid_rows = [idx for idx in row_indices if idx in new_df.index]
    preview = _preview(new_df, valid_rows, flag_column, flag_value)
    new_df.loc[valid_rows, flag_column] = flag_value
    return new_df, preview


MAX_COLUMN_NAME = 100


def add_column(df: pd.DataFrame, new_column: str, value=None, source_column: str | None = None,
               after_column: str | None = None, formula: str | None = None) -> tuple[pd.DataFrame, list]:
    """Adds one column: empty, one fixed value, a copy of a column, or
    calculated from other columns with a formula such as
    2 * ([Width] + [Height]). Formulas are parsed and checked by
    column_formula.py, never executed as code, so this stays within the
    rule that no model-written code changes data. Existing columns are
    not touched."""
    name = (new_column or "").strip()
    if not name:
        raise EditValidationError("The new column needs a name.")
    if len(name) > MAX_COLUMN_NAME:
        raise EditValidationError(f"Column names are limited to {MAX_COLUMN_NAME} characters.")
    if name.lower() in {str(c).strip().lower() for c in df.columns}:
        raise EditValidationError(f"A column named '{name}' already exists.")
    given = [bool(source_column), value not in (None, ""), bool((formula or "").strip())]
    if sum(given) > 1:
        raise EditValidationError("Give only one of: a fixed value, a column to copy, or a formula.")
    if source_column and source_column not in df.columns:
        raise EditValidationError(f"Column '{source_column}' does not exist.")
    if after_column and after_column not in df.columns:
        raise EditValidationError(f"Column '{after_column}' does not exist.")

    new_df = df.copy(deep=True)
    if (formula or "").strip():
        try:
            data = column_formula.evaluate(formula, new_df)
        except column_formula.FormulaError as e:
            raise EditValidationError(str(e)) from e
    elif source_column:
        data = new_df[source_column].copy()
    elif value not in (None, ""):
        data = pd.Series([value] * len(new_df), index=new_df.index, dtype=object)
    else:
        data = pd.Series([None] * len(new_df), index=new_df.index, dtype=object)

    position = list(new_df.columns).index(after_column) + 1 if after_column else len(new_df.columns)
    new_df.insert(position, name, data)
    preview = [{"row": int(i), "column": name, "before": None, "after": data.at[i]} for i in new_df.index[:5]]
    return new_df, preview


# The closed set of operations the agent is allowed to invoke by name.
# Adding a new capability means adding a reviewed function here - never
# means loosening this into "run this code the model wrote".
ALLOWED_OPERATIONS = {
    "fill_missing_value": fill_missing_value,
    "fill_missing_value_bulk": fill_missing_value_bulk,
    "standardize_value": standardize_value,
    "flag_rows": flag_rows,
    "add_column": add_column,
}


def apply_operation(df: pd.DataFrame, operation: str, **kwargs) -> tuple[pd.DataFrame, list]:
    if operation not in ALLOWED_OPERATIONS:
        raise EditValidationError(
            f"'{operation}' is not an allowed edit operation. Allowed: {list(ALLOWED_OPERATIONS)}"
        )
    logger.info("Applying edit operation=%s kwargs=%s", operation, {k: v for k, v in kwargs.items() if k != "row_indices"})
    return ALLOWED_OPERATIONS[operation](df, **kwargs)
